import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-blue-500">
          <ul className="max-w-6xl mx-auto px-5 text-white flex gap-x-7">
            <li>
              <h1 className="text-3xl font-bold pt-2 font-body">
                <Link href="/">My Blog</Link>
              </h1>
            </li>
            <li className="p-4">
              <Link href="/write">글쓰기</Link>
            </li>
          </ul>
        </nav>
        <div className="px-5 max-w-6xl mx-auto pt-10">{children}</div>
      </body>
    </html>
  );
}
